//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRoomDig.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AjustaScrPos
    {
        public int id { get; set; }
        public decimal PrdGrillaAncho { get; set; }
        public decimal PrdGrillaAlto { get; set; }
        public decimal AnotaGrillaAncho { get; set; }
        public decimal AnotaGrillaNotaTop { get; set; }
        public decimal AnotaGrillaNotaAncho { get; set; }
        public decimal TabsGralCant { get; set; }
        public decimal TabsGralCols { get; set; }
        public decimal TabsGralFlecha { get; set; }
        public decimal GrillaPedidoTop { get; set; }
        public decimal GrillaPedidoAlto { get; set; }
        public decimal GrillaPedidoLeft { get; set; }
        public decimal GrillaPedidoIntAlto { get; set; }
        public decimal GrillaPedidoMontoTop { get; set; }
        public decimal GrillaPagosTop { get; set; }
        public decimal GrillaPagosLeft { get; set; }
        public decimal VerprodVentaTop { get; set; }
        public decimal VerprodVentaLeft { get; set; }
        public decimal VerprodVentaAlto { get; set; }
        public bool VerprodVentaVisible { get; set; }
        public Nullable<int> GrillaPedidoAncho { get; set; }
        public Nullable<int> GrillaProdAncho { get; set; }
        public Nullable<int> GrillaItemsAncho { get; set; }
        public string DescripConfig { get; set; }
        public Nullable<int> PrdGrillaTop { get; set; }
        public Nullable<int> PrdGrillaLeft { get; set; }
        public Nullable<int> GrillaProdObservaAncho { get; set; }
    }
}
