//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRoomDig.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class alquiler_personas
    {
        public int id_Alquiler { get; set; }
        public Nullable<int> adultoCant { get; set; }
        public Nullable<decimal> adultoTarifa { get; set; }
        public Nullable<int> ninoCant { get; set; }
        public Nullable<decimal> ninoTarifa { get; set; }
        public Nullable<int> bebeCant { get; set; }
        public Nullable<decimal> bebeTarifa { get; set; }
    }
}
