//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRoomDig.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class alquiler_puc
    {
        public int id_Alquiler { get; set; }
        public int id_tipoPersona { get; set; }
        public int orden { get; set; }
        public Nullable<int> cant { get; set; }
        public Nullable<int> producto { get; set; }
        public Nullable<decimal> @base { get; set; }
        public Nullable<int> id_tipiva { get; set; }
        public Nullable<decimal> tariva { get; set; }
        public Nullable<bool> variable { get; set; }
        public Nullable<bool> ALIMENTACION { get; set; }
    }
}
