//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRoomDig.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class alquilerTrConcepto
    {
        public int id_alquiler { get; set; }
        public int id_productos { get; set; }
        public Nullable<bool> inicial { get; set; }
        public Nullable<decimal> tarifa { get; set; }
        public Nullable<int> id_tipIva { get; set; }
        public Nullable<decimal> porcImpto { get; set; }
        public Nullable<decimal> costo { get; set; }
        public Nullable<bool> siImpto { get; set; }
    }
}
