//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRoomDig.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class alquiler_alimentacion
    {
        public int id_alquiler { get; set; }
        public Nullable<int> desayunoCant { get; set; }
        public Nullable<decimal> desayunoTarifa { get; set; }
        public Nullable<int> refrigAmCant { get; set; }
        public Nullable<decimal> refrigAmTarifa { get; set; }
        public Nullable<int> AlmuerzoCant { get; set; }
        public Nullable<decimal> AlmuerzoTarifa { get; set; }
        public Nullable<int> refrigPmCant { get; set; }
        public Nullable<decimal> refrigPmTarifa { get; set; }
        public Nullable<int> CenaCant { get; set; }
        public Nullable<decimal> CenaTarifa { get; set; }
        public Nullable<int> ID_TIPOPERSONA { get; set; }
    }
}
