//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRoomDig.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANEXO
    {
        public int numeros { get; set; }
        public string letra { get; set; }
        public Nullable<bool> cabezera { get; set; }
        public Nullable<bool> productos { get; set; }
        public Nullable<bool> pago { get; set; }
        public string contenido { get; set; }
        public Nullable<bool> centrar { get; set; }
    }
}
