//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRoomDig.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class anul
    {
        public int id { get; set; }
        public int id_pedidos { get; set; }
        public int id_cauanuls { get; set; }
        public string maquina { get; set; }
        public decimal valor { get; set; }
        public string autoriza { get; set; }
        public string observa { get; set; }
        public System.DateTime fec_graba { get; set; }
        public string usuario { get; set; }
        public Nullable<int> id_facturas { get; set; }
        public string descrip { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<bool> imprime { get; set; }
        public Nullable<int> id_consumos { get; set; }
    
        public virtual cauanul cauanul { get; set; }
    }
}
