//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRoomDig.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class areasAutom
    {
        public int id { get; set; }
        public Nullable<int> DiaSemana { get; set; }
        public Nullable<System.DateTime> Hora { get; set; }
        public Nullable<int> idArea { get; set; }
        public Nullable<int> idDevice { get; set; }
        public Nullable<bool> OnOff { get; set; }
    }
}
