//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRoomDig.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class auditoriaNocturna
    {
        public int numInt { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string usuario { get; set; }
        public Nullable<int> maquina { get; set; }
        public Nullable<int> habOcupada { get; set; }
        public Nullable<int> habDisponible { get; set; }
        public Nullable<int> HabMantenimiento { get; set; }
        public Nullable<int> habAseo { get; set; }
        public Nullable<int> habReservada { get; set; }
        public Nullable<int> habComplem { get; set; }
        public Nullable<int> habHouseUse { get; set; }
        public Nullable<int> habOfertadas { get; set; }
        public Nullable<int> camasOfertadas { get; set; }
        public Nullable<int> camasOcupadas { get; set; }
        public Nullable<int> huespNacional { get; set; }
        public Nullable<int> huespInter { get; set; }
        public Nullable<decimal> porcOcupa { get; set; }
        public Nullable<decimal> tarifaProm { get; set; }
        public Nullable<int> reservaIngreso { get; set; }
        public Nullable<int> reservaNoShow { get; set; }
        public Nullable<int> reservaCancela { get; set; }
        public Nullable<int> checkInn { get; set; }
        public Nullable<int> checkOut { get; set; }
        public Nullable<int> EstadiaExt { get; set; }
        public Nullable<int> SalidaInes { get; set; }
    }
}
