//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRoomDig.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class auditoriaNocHabita
    {
        public int numInt { get; set; }
        public int id_habita { get; set; }
        public int id_suites { get; set; }
        public Nullable<int> paxOferta { get; set; }
        public Nullable<int> paxVendidas { get; set; }
        public Nullable<int> id_estado { get; set; }
        public Nullable<int> id_pedido { get; set; }
        public Nullable<decimal> tarifa { get; set; }
    }
}
