//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRoomDig.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bitacora
    {
        public int id { get; set; }
        public System.DateTime fecha { get; set; }
        public string nota { get; set; }
        public string usuario { get; set; }
        public Nullable<int> id_novedad { get; set; }
        public Nullable<short> relevancia { get; set; }
        public Nullable<bool> terminado { get; set; }
        public Nullable<bool> revisado { get; set; }
        public string usuario_revisa { get; set; }
        public Nullable<int> idNovedadDetalle { get; set; }
    
        public virtual novedad novedad { get; set; }
    }
}
