//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRoomDig.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CABE_OC
    {
        public int ID_OC { get; set; }
        public Nullable<int> ID_PROVEEDOR { get; set; }
        public Nullable<System.DateTime> FECHA_PEDIDO { get; set; }
        public Nullable<System.DateTime> FECHA_PAGO { get; set; }
        public string TERMINOS { get; set; }
        public Nullable<int> ID_CABE_RI { get; set; }
    }
}
