//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRoomDig.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class camform
    {
        public int id_platoprod { get; set; }
        public int id_platomed { get; set; }
        public int id_comProd { get; set; }
        public int id_ComMedi { get; set; }
        public int id_OpcProd { get; set; }
        public int id_OpcMed { get; set; }
        public Nullable<float> id_OpcCant { get; set; }
    }
}
