//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRoomDig.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cargue
    {
        public int idCargue { get; set; }
        public int idHab { get; set; }
        public Nullable<int> idServicio { get; set; }
        public string idTarjeta { get; set; }
        public Nullable<int> cantVisita { get; set; }
        public Nullable<int> puntos { get; set; }
        public Nullable<int> puntosCanjea { get; set; }
        public string idPromo { get; set; }
        public string idPremio { get; set; }
        public System.DateTime fecGraba { get; set; }
        public string usuario { get; set; }
        public Nullable<decimal> vlBono { get; set; }
        public Nullable<int> idPedido { get; set; }
    }
}
