//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRoomDig.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CENTROC
    {
        public int ID { get; set; }
        public string NAME { get; set; }
        public Nullable<int> ID_BODEGAS { get; set; }
        public Nullable<int> ID_SECCION { get; set; }
        public Nullable<int> ID_FRMSHOW { get; set; }
    }
}
