//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRoomDig.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class clasepista
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> TIEMPO { get; set; }
        public Nullable<bool> MAIL { get; set; }
        public Nullable<int> bitacora { get; set; }
        public Nullable<int> tipo { get; set; }
        public Nullable<int> PRIORIDAD { get; set; }
    }
}
