//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRoomDig.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cliente
    {
        public int numint { get; set; }
        public string id { get; set; }
        public Nullable<int> tipodoc { get; set; }
        public string name { get; set; }
        public Nullable<int> sexo { get; set; }
        public Nullable<System.DateTime> nace { get; set; }
        public string dir { get; set; }
        public Nullable<int> id_ciudad { get; set; }
        public string tel { get; set; }
        public Nullable<int> nacionalidad { get; set; }
        public Nullable<int> id_pedido { get; set; }
        public Nullable<int> id_empresas { get; set; }
        public Nullable<int> id_mesa { get; set; }
        public Nullable<int> id_cargo { get; set; }
        public Nullable<bool> archivar { get; set; }
        public Nullable<bool> comision { get; set; }
        public string primname { get; set; }
        public string segname { get; set; }
        public string primapel { get; set; }
        public string segapel { get; set; }
        public Nullable<int> id_procedencia { get; set; }
        public Nullable<int> id_destino { get; set; }
        public Nullable<int> id_reserva { get; set; }
        public string Gustos { get; set; }
        public string email { get; set; }
        public Nullable<bool> MENUDEO { get; set; }
        public string descrip { get; set; }
        public string FAX { get; set; }
        public Nullable<int> ID_PAIS { get; set; }
        public string CONTACTO { get; set; }
        public string USUARIO { get; set; }
        public Nullable<System.DateTime> FEC_GRABA { get; set; }
        public Nullable<bool> ACTIVO { get; set; }
        public Nullable<int> tipo { get; set; }
        public Nullable<int> idtercero { get; set; }
        public Nullable<bool> empresa { get; set; }
        public Nullable<int> CCFrom { get; set; }
        public Nullable<bool> incognito { get; set; }
        public Nullable<bool> fastCheckOut { get; set; }
        public Nullable<bool> mailing { get; set; }
        public Nullable<int> idIdioma { get; set; }
        public Nullable<int> idSector { get; set; }
        public string tCelular { get; set; }
        public string tContacto { get; set; }
        public Nullable<int> idRegimen { get; set; }
        public Nullable<int> idContribuyente { get; set; }
        public Nullable<int> idCIUU { get; set; }
        public Nullable<bool> siAuto { get; set; }
        public Nullable<bool> siFuente { get; set; }
        public Nullable<bool> siReteiva { get; set; }
        public Nullable<bool> siReteICA { get; set; }
        public string tContaCartera { get; set; }
        public string tTelefCartera { get; set; }
        public string tCupo { get; set; }
        public Nullable<int> idPlanAsig { get; set; }
        public string tDescuento { get; set; }
        public string tPlazoVence { get; set; }
        public Nullable<bool> siAutoriza { get; set; }
        public string tNotaEmpre { get; set; }
        public Nullable<bool> siWebBull { get; set; }
        public Nullable<int> idCiiu { get; set; }
    }
}
