//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRoomDig.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class clientes_Desayuno
    {
        public int id { get; set; }
        public Nullable<int> idTercero { get; set; }
        public Nullable<System.DateTime> dia { get; set; }
        public Nullable<bool> Desayuna { get; set; }
        public Nullable<int> idPedido { get; set; }
    }
}
