//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRoomDig.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class comanda
    {
        public int id_areas { get; set; }
        public int id_grupos { get; set; }
        public string impresora { get; set; }
        public Nullable<int> id_bodegas { get; set; }
    
        public virtual area area { get; set; }
        public virtual bodega bodega { get; set; }
        public virtual grupos grupos { get; set; }
    }
}
