//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRoomDig.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class controlHerramienta
    {
        public int id { get; set; }
        public Nullable<int> idHerramienta { get; set; }
        public Nullable<int> idBodegaSal { get; set; }
        public Nullable<int> idBodegaEnt { get; set; }
        public Nullable<int> idClienteSal { get; set; }
        public Nullable<int> idClienteEnt { get; set; }
        public Nullable<int> idRecibeIni { get; set; }
        public Nullable<int> idRecibeFin { get; set; }
        public Nullable<int> idEntregaIni { get; set; }
        public Nullable<int> idEntregaFin { get; set; }
        public Nullable<bool> finaliza { get; set; }
        public Nullable<System.DateTime> fechaSalida { get; set; }
        public Nullable<System.DateTime> fechaEntrada { get; set; }
        public string observaciones { get; set; }
    }
}
