//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRoomDig.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class conver
    {
        public int id_detmedidas_A { get; set; }
        public int id_detmedidas_B { get; set; }
        public Nullable<decimal> cantidad_A { get; set; }
        public Nullable<decimal> cantidad_B { get; set; }
    
        public virtual detmedida detmedida { get; set; }
        public virtual detmedida detmedida1 { get; set; }
    }
}
