//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRoomDig.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class conver_spec
    {
        public int id_productos_nec { get; set; }
        public int id_detmedidas_nec { get; set; }
        public int id_productos_sac { get; set; }
        public int id_detmedidas_sac { get; set; }
        public Nullable<decimal> cant_sac { get; set; }
        public Nullable<decimal> cant_nec { get; set; }
        public Nullable<int> nivel { get; set; }
    }
}
