//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRoomDig.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class correo
    {
        public int id { get; set; }
        public string area { get; set; }
        public string correo1 { get; set; }
        public string clave { get; set; }
        public string host { get; set; }
        public Nullable<int> port { get; set; }
        public Nullable<bool> emailSSL { get; set; }
    }
}
