//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRoomDig.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cotizacion_detalle
    {
        public int id_cotizacion { get; set; }
        public Nullable<int> id_suites { get; set; }
        public Nullable<System.DateTime> fec_in { get; set; }
        public Nullable<System.DateTime> fec_out { get; set; }
        public Nullable<int> adultos { get; set; }
        public Nullable<int> menores { get; set; }
        public Nullable<int> noches { get; set; }
        public Nullable<decimal> valorXnoche { get; set; }
        public Nullable<decimal> subtotal { get; set; }
    }
}
