//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRoomDig.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cptoingr
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cptoingr()
        {
            this.ingresos = new HashSet<ingreso>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<bool> cant { get; set; }
        public Nullable<bool> descrip { get; set; }
        public Nullable<bool> obser { get; set; }
        public Nullable<decimal> valor { get; set; }
        public Nullable<int> id_frmpagos { get; set; }
    
        public virtual frmpago frmpago { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ingreso> ingresos { get; set; }
    }
}
