//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRoomDig.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cptoegre
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<bool> cant { get; set; }
        public Nullable<bool> descrip { get; set; }
        public Nullable<bool> favor { get; set; }
        public Nullable<bool> nit { get; set; }
        public Nullable<bool> Obser { get; set; }
        public Nullable<decimal> valor { get; set; }
        public Nullable<bool> modifica { get; set; }
        public Nullable<bool> clave { get; set; }
    }
}
