//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRoomDig.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CtrlCama
    {
        public int id { get; set; }
        public Nullable<int> Id_Camarera { get; set; }
        public Nullable<System.DateTime> Fec_Ingreso { get; set; }
        public Nullable<System.DateTime> Fec_Salida { get; set; }
        public Nullable<int> Id_TipoLabor { get; set; }
        public Nullable<int> Id_Mesas { get; set; }
        public string Observaciones { get; set; }
        public Nullable<int> id_pedidos { get; set; }
        public Nullable<int> id_estado { get; set; }
        public Nullable<System.DateTime> fec_entrega { get; set; }
        public string usuario { get; set; }
        public Nullable<int> idMaquina { get; set; }
        public Nullable<System.DateTime> fec_supervisa { get; set; }
    }
}
