//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRoomDig.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DECOMAPA
    {
        public int AUTOM { get; set; }
        public Nullable<int> MAQUINA { get; set; }
        public Nullable<int> BLOQUE { get; set; }
        public Nullable<int> COORX { get; set; }
        public Nullable<int> COORY { get; set; }
        public Nullable<bool> LABEL { get; set; }
        public Nullable<bool> IMAGE { get; set; }
        public string FONT { get; set; }
        public Nullable<int> SIZE { get; set; }
        public Nullable<bool> ITALIC { get; set; }
        public Nullable<bool> BOLD { get; set; }
        public string NAME { get; set; }
        public Nullable<int> HEIGHT { get; set; }
        public Nullable<int> WIDHT { get; set; }
        public Nullable<int> COLORLETRA { get; set; }
        public Nullable<int> COLORFONDO { get; set; }
    }
}
