//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRoomDig.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class det_serv
    {
        public int id_pedido { get; set; }
        public int id_servicio { get; set; }
        public int id_tipos { get; set; }
        public Nullable<bool> inicial { get; set; }
        public Nullable<decimal> seguro { get; set; }
        public Nullable<int> id_tempo { get; set; }
        public Nullable<int> id_tiposer { get; set; }
        public Nullable<int> id_clases { get; set; }
        public string observa { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<decimal> valor { get; set; }
        public Nullable<decimal> vl_iva { get; set; }
        public Nullable<decimal> vl_tariva { get; set; }
        public Nullable<int> id_estado { get; set; }
        public string usuario { get; set; }
        public Nullable<System.DateTime> fec_graba { get; set; }
        public Nullable<int> id_atiende { get; set; }
        public string prefijo { get; set; }
        public Nullable<int> id_facturas { get; set; }
        public Nullable<int> id_anula { get; set; }
        public string ti_proms { get; set; }
        public Nullable<int> id_proms { get; set; }
        public Nullable<int> relitem { get; set; }
        public int id_medio { get; set; }
        public Nullable<int> numid { get; set; }
        public Nullable<int> comanda { get; set; }
        public Nullable<decimal> dscto { get; set; }
        public Nullable<int> tiempo { get; set; }
        public Nullable<int> persona { get; set; }
        public Nullable<int> id_dscto { get; set; }
        public Nullable<int> maquina { get; set; }
        public string autoriza { get; set; }
        public Nullable<System.DateTime> fec_autoriza { get; set; }
        public Nullable<int> id_tariva { get; set; }
        public string usuario_graba { get; set; }
        public string admin_graba { get; set; }
        public Nullable<bool> nuevo { get; set; }
        public Nullable<int> alterno { get; set; }
        public Nullable<decimal> COSTO { get; set; }
        public Nullable<decimal> item1 { get; set; }
        public Nullable<decimal> item2 { get; set; }
        public Nullable<decimal> item3 { get; set; }
        public Nullable<int> PedAnter { get; set; }
        public Nullable<decimal> @base { get; set; }
        public Nullable<decimal> ValorNeto { get; set; }
        public Nullable<decimal> Descuento { get; set; }
        public Nullable<decimal> AJUSTES { get; set; }
        public Nullable<decimal> IMPOCONSUMO { get; set; }
        public Nullable<int> ID_CANT { get; set; }
        public Nullable<int> ID_PRODUCTOS { get; set; }
        public Nullable<decimal> Ahorro { get; set; }
        public Nullable<int> IdTurnoGraba { get; set; }
        public Nullable<int> IdTurnoFactura { get; set; }
        public Nullable<int> IdApp { get; set; }
        public Nullable<int> pedidoAnterior { get; set; }
        public Nullable<System.DateTime> fecTerminal { get; set; }
        public string nOrdenPedido { get; set; }
    }
}
