//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRoomDig.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle
    {
        public int id_pedidos { get; set; }
        public int id_consumos { get; set; }
        public Nullable<int> item { get; set; }
        public Nullable<int> id_productos { get; set; }
        public Nullable<int> id_detmedidas { get; set; }
        public Nullable<short> cantidad { get; set; }
        public Nullable<decimal> valor { get; set; }
        public Nullable<decimal> vl_iva { get; set; }
        public Nullable<decimal> vl_tariva { get; set; }
        public Nullable<int> id_detestados { get; set; }
        public string usuario { get; set; }
        public Nullable<System.DateTime> fec_graba { get; set; }
        public string prefijo { get; set; }
        public Nullable<int> factura { get; set; }
        public Nullable<int> id_meseros { get; set; }
        public Nullable<int> id_temps { get; set; }
        public Nullable<int> id_anula { get; set; }
        public Nullable<int> ventas { get; set; }
        public string llevar { get; set; }
        public Nullable<int> id_proms { get; set; }
        public string ti_proms { get; set; }
        public Nullable<int> relitem { get; set; }
        public Nullable<bool> proms { get; set; }
        public string autoriza { get; set; }
        public Nullable<System.DateTime> fec_autoriza { get; set; }
        public string observa { get; set; }
        public Nullable<decimal> dscto { get; set; }
        public Nullable<int> comanda { get; set; }
        public Nullable<int> id_lugar { get; set; }
        public Nullable<int> id_medio { get; set; }
        public Nullable<int> numid { get; set; }
        public Nullable<int> id_dscto { get; set; }
        public Nullable<int> Maquina { get; set; }
        public Nullable<int> id_tariva { get; set; }
        public string usuario_graba { get; set; }
        public string admin_graba { get; set; }
        public string prefcom_printer { get; set; }
        public Nullable<int> com_printer { get; set; }
        public Nullable<int> secc { get; set; }
        public Nullable<bool> entrega { get; set; }
        public Nullable<System.DateTime> fec_entrega { get; set; }
        public string usuario_entrega { get; set; }
        public Nullable<int> id_volante { get; set; }
        public Nullable<bool> nuevo { get; set; }
        public Nullable<int> alterno { get; set; }
        public Nullable<int> altmedio { get; set; }
        public Nullable<int> altped { get; set; }
        public Nullable<decimal> COSTO { get; set; }
        public Nullable<int> PedAnter { get; set; }
        public Nullable<int> PedLink { get; set; }
        public Nullable<decimal> item1 { get; set; }
        public Nullable<decimal> item2 { get; set; }
        public Nullable<decimal> item3 { get; set; }
        public Nullable<decimal> @base { get; set; }
        public Nullable<decimal> ValorNeto { get; set; }
        public Nullable<decimal> Descuento { get; set; }
        public Nullable<decimal> AJUSTES { get; set; }
        public Nullable<bool> LLEVADO { get; set; }
        public Nullable<System.DateTime> FEC_LLEVADO { get; set; }
        public Nullable<bool> DEMORA { get; set; }
        public Nullable<decimal> IMPOCONSUMO { get; set; }
        public Nullable<decimal> Ahorro { get; set; }
        public Nullable<int> IdTurnoGraba { get; set; }
        public Nullable<int> IdTurnoFactura { get; set; }
        public Nullable<int> IdApp { get; set; }
        public Nullable<int> pedidoAnterior { get; set; }
        public Nullable<int> numVoucher { get; set; }
        public Nullable<System.DateTime> fecTerminal { get; set; }
        public string nOrdenPedido { get; set; }
    
        public virtual detestado detestado { get; set; }
        public virtual detmedida detmedida { get; set; }
        public virtual mesero mesero { get; set; }
        public virtual producto producto { get; set; }
        public virtual temp temp { get; set; }
    }
}
