//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRoomDig.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detivafact
    {
        public string prefijo { get; set; }
        public int id_facturas { get; set; }
        public int id_tipiva { get; set; }
        public decimal tarifa { get; set; }
        public Nullable<decimal> compra { get; set; }
        public Nullable<decimal> @base { get; set; }
        public Nullable<decimal> iva { get; set; }
        public Nullable<int> id_detestados { get; set; }
        public Nullable<int> Tipo { get; set; }
        public Nullable<decimal> descuento { get; set; }
    }
}
