//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRoomDig.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DISPOHORA
    {
        public int auto { get; set; }
        public Nullable<int> dia { get; set; }
        public Nullable<int> hors { get; set; }
        public Nullable<decimal> dispon { get; set; }
        public Nullable<int> salidas { get; set; }
        public Nullable<int> devuelto { get; set; }
        public Nullable<decimal> alta { get; set; }
        public string hora { get; set; }
        public Nullable<int> entran { get; set; }
        public Nullable<decimal> valorservicio { get; set; }
        public Nullable<decimal> valorconsum { get; set; }
        public Nullable<decimal> total { get; set; }
        public Nullable<int> MES { get; set; }
        public Nullable<int> ANIO { get; set; }
        public Nullable<int> DIASEM { get; set; }
        public Nullable<int> ENTRANFACT { get; set; }
    }
}
