//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRoomDig.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class egreso
    {
        public int id { get; set; }
        public Nullable<int> id_cptoegre { get; set; }
        public Nullable<int> cant { get; set; }
        public string afavor { get; set; }
        public string anit { get; set; }
        public string descrip { get; set; }
        public string observa { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<decimal> valor { get; set; }
        public string usuario { get; set; }
        public string autoriza { get; set; }
        public Nullable<int> id_detestados { get; set; }
        public Nullable<bool> nit { get; set; }
        public Nullable<bool> graba { get; set; }
        public string plantilla { get; set; }
        public Nullable<int> maquina { get; set; }
        public Nullable<int> id_crespo { get; set; }
        public Nullable<bool> efectivo { get; set; }
    
        public virtual detestado detestado { get; set; }
    }
}
