//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRoomDig.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class evidencia
    {
        public System.Guid id { get; set; }
        public string codeTipoEvid { get; set; }
        public string codeCarpeta { get; set; }
        public int idIdentifica { get; set; }
        public int idSerialNum { get; set; }
        public byte[] evidencia1 { get; set; }
        public string descripcion { get; set; }
        public string fileName { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string usuario { get; set; }
    }
}
