//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRoomDig.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class factura
    {
        public int tipo { get; set; }
        public string prefijo { get; set; }
        public int id { get; set; }
        public Nullable<bool> pendiente { get; set; }
        public int id_pedidos { get; set; }
        public Nullable<decimal> total { get; set; }
        public Nullable<decimal> valor { get; set; }
        public Nullable<decimal> dscto { get; set; }
        public Nullable<decimal> propina { get; set; }
        public Nullable<decimal> iva { get; set; }
        public Nullable<decimal> ivadscto { get; set; }
        public Nullable<decimal> seguro { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string usuario { get; set; }
        public Nullable<int> id_detestados { get; set; }
        public Nullable<int> clase { get; set; }
        public Nullable<int> id_meseros { get; set; }
        public Nullable<bool> empresa { get; set; }
        public Nullable<int> id_cliente { get; set; }
        public Nullable<int> id_maquina { get; set; }
        public Nullable<int> Comanda { get; set; }
        public Nullable<bool> sPrint { get; set; }
        public Nullable<int> alterno { get; set; }
        public Nullable<decimal> item1 { get; set; }
        public Nullable<decimal> item2 { get; set; }
        public Nullable<decimal> item3 { get; set; }
        public Nullable<int> ID_RESOLUCION { get; set; }
        public Nullable<decimal> RETEFUENTE { get; set; }
        public Nullable<decimal> CREE { get; set; }
        public Nullable<decimal> BASES { get; set; }
        public Nullable<bool> DOMICILIO { get; set; }
        public Nullable<int> ID_RESERVAS { get; set; }
        public Nullable<decimal> RETEIVA { get; set; }
        public Nullable<decimal> RETEICA { get; set; }
        public Nullable<System.DateTime> FECVENCE { get; set; }
        public Nullable<int> idTipoFactura { get; set; }
        public string notaFactura { get; set; }
        public Nullable<int> IdApp { get; set; }
        public Nullable<System.DateTime> checkout { get; set; }
        public Nullable<int> personas { get; set; }
        public string nOrdenPedido { get; set; }
    
        public virtual detestado detestado { get; set; }
        public virtual mesero mesero { get; set; }
    }
}
