//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRoomDig.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class formula
    {
        public int id_productos_ini { get; set; }
        public int id_detmedidas_ini { get; set; }
        public int id_productos { get; set; }
        public int id_detmedidas { get; set; }
        public Nullable<decimal> cantidad { get; set; }
        public Nullable<bool> cambio { get; set; }
        public Nullable<bool> NOBASE { get; set; }
    
        public virtual detmedida detmedida { get; set; }
        public virtual producto producto { get; set; }
    }
}
