//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRoomDig.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class frmpago
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public frmpago()
        {
            this.cptoingrs = new HashSet<cptoingr>();
            this.detfacturas = new HashSet<detfactura>();
            this.toolFrmPagos = new HashSet<toolFrmPago>();
            this.toolFrmPagos1 = new HashSet<toolFrmPago>();
            this.toolFrmPagos2 = new HashSet<toolFrmPago>();
            this.toolFrmPagos3 = new HashSet<toolFrmPago>();
            this.toolFrmPagos4 = new HashSet<toolFrmPago>();
            this.ingresos = new HashSet<ingreso>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string observa { get; set; }
        public int id_tippagos { get; set; }
        public Nullable<bool> control { get; set; }
        public Nullable<bool> autoriza { get; set; }
        public Nullable<bool> clave { get; set; }
        public Nullable<bool> exacto { get; set; }
        public Nullable<bool> cambio { get; set; }
        public Nullable<bool> no { get; set; }
        public Nullable<bool> nota { get; set; }
        public Nullable<bool> cliente { get; set; }
        public Nullable<bool> propina { get; set; }
        public Nullable<int> ctvocontrol { get; set; }
        public Nullable<bool> tipo { get; set; }
        public Nullable<bool> unico { get; set; }
        public Nullable<bool> CARTERA { get; set; }
        public Nullable<bool> siReserva { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cptoingr> cptoingrs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detfactura> detfacturas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<toolFrmPago> toolFrmPagos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<toolFrmPago> toolFrmPagos1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<toolFrmPago> toolFrmPagos2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<toolFrmPago> toolFrmPagos3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<toolFrmPago> toolFrmPagos4 { get; set; }
        public virtual tippago tippago { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ingreso> ingresos { get; set; }
    }
}
