//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRoomDig.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class frmshow
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> id_showconsec { get; set; }
        public Nullable<bool> acumula { get; set; }
        public string PUC { get; set; }
        public Nullable<decimal> tribut { get; set; }
        public Nullable<int> INVENPUC { get; set; }
        public Nullable<int> DSCTOPUC { get; set; }
        public Nullable<int> COSTOPUC { get; set; }
    }
}
