//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRoomDig.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INCONSENSOR
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> trama1 { get; set; }
        public Nullable<int> trama2 { get; set; }
        public Nullable<int> trama3 { get; set; }
    }
}
