//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRoomDig.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ingreso
    {
        public int id { get; set; }
        public Nullable<int> id_frmpago { get; set; }
        public Nullable<int> id_cptoingr { get; set; }
        public Nullable<int> cant { get; set; }
        public string descrip { get; set; }
        public string observa { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<decimal> valor { get; set; }
        public string usuario { get; set; }
        public Nullable<int> id_detestados { get; set; }
        public string admin { get; set; }
        public Nullable<int> id_bancos { get; set; }
        public string autoriza { get; set; }
    
        public virtual banco banco { get; set; }
        public virtual cptoingr cptoingr { get; set; }
        public virtual detestado detestado { get; set; }
        public virtual frmpago frmpago { get; set; }
    }
}
