//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRoomDig.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Instancia
    {
        public int id { get; set; }
        public string Hotel { get; set; }
        public string instancia1 { get; set; }
        public string BDName { get; set; }
        public string sqlName { get; set; }
        public string sqlKey { get; set; }
        public string sqlFecha { get; set; }
    }
}
