//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRoomDig.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KPItrue
    {
        public int KPI { get; set; }
        public int LLAVE1 { get; set; }
        public int LLAVE2 { get; set; }
        public string DESCRIP { get; set; }
        public Nullable<int> MIN { get; set; }
        public Nullable<int> MAX { get; set; }
        public Nullable<int> IDENTIF { get; set; }
    }
}
