//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRoomDig.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class logReservasW
    {
        public int id { get; set; }
        public Nullable<System.DateTimeOffset> fechaIn { get; set; }
        public string metodo { get; set; }
        public Nullable<System.DateTimeOffset> fechaOut { get; set; }
        public string Resultado { get; set; }
    }
}
