//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRoomDig.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class maquina
    {
        public int id { get; set; }
        public string name { get; set; }
        public string imprime { get; set; }
        public Nullable<int> id_bodegas { get; set; }
        public Nullable<int> Id_zona { get; set; }
        public Nullable<int> Id_mesas { get; set; }
        public Nullable<int> mPed { get; set; }
        public Nullable<int> mCom { get; set; }
        public Nullable<bool> VerSolo { get; set; }
        public Nullable<int> SALESURTIR { get; set; }
        public Nullable<int> SALEVOLANTE { get; set; }
        public Nullable<int> SALEDEFECTO { get; set; }
        public Nullable<bool> FACTURAPEQ { get; set; }
        public Nullable<bool> FACTURAHOTEL { get; set; }
        public Nullable<bool> COBROPERSONA { get; set; }
        public Nullable<bool> registroRapido { get; set; }
        public Nullable<bool> pantPorteria { get; set; }
        public Nullable<bool> DEMO { get; set; }
        public Nullable<bool> hibrido { get; set; }
        public Nullable<int> SENSOR { get; set; }
        public string SerialNO { get; set; }
        public string prefijo { get; set; }
        public string numFact { get; set; }
        public string Resolucion { get; set; }
        public string cualListado { get; set; }
        public Nullable<int> cantColPOS { get; set; }
        public string Responsable { get; set; }
        public string Nit { get; set; }
        public string establecimiento { get; set; }
        public Nullable<bool> OPCCLIENTE { get; set; }
        public Nullable<int> habAlto { get; set; }
        public Nullable<int> habAncho { get; set; }
        public Nullable<int> habLetraSize { get; set; }
        public Nullable<bool> OpcConexion { get; set; }
        public Nullable<bool> viewInstances { get; set; }
        public string printer { get; set; }
        public Nullable<int> taxisTicket { get; set; }
        public Nullable<int> nOrdenPedido { get; set; }
    }
}
