//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRoomDig.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class memo1
    {
        public int id_maquina { get; set; }
        public int id_comdia { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<System.DateTime> fecha_cierre { get; set; }
        public string prefijo { get; set; }
        public Nullable<int> numini { get; set; }
        public Nullable<int> numfin { get; set; }
        public Nullable<int> cttran { get; set; }
        public Nullable<decimal> vltran { get; set; }
        public Nullable<System.DateTime> fechacom { get; set; }
        public string usuario { get; set; }
        public Nullable<decimal> seguro { get; set; }
        public string CD { get; set; }
        public Nullable<bool> CONTAB { get; set; }
    }
}
