//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRoomDig.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class memo3
    {
        public int id_maquina { get; set; }
        public int id_comdia { get; set; }
        public string id_medio { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<decimal> valor { get; set; }
        public Nullable<decimal> propina { get; set; }
    }
}
