//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRoomDig.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class memo2
    {
        public int id_maquina { get; set; }
        public int id_comdia { get; set; }
        public int id_tipo { get; set; }
        public int id_tarifa { get; set; }
        public Nullable<decimal> ventas { get; set; }
        public Nullable<decimal> gravado { get; set; }
        public Nullable<decimal> compra { get; set; }
    }
}
