//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRoomDig.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mensaje
    {
        public int id { get; set; }
        public Nullable<int> id_mesas { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> id_pedidos { get; set; }
        public string tipo { get; set; }
        public string contenido { get; set; }
        public Nullable<bool> mecanismo { get; set; }
    }
}
