//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRoomDig.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mesero
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mesero()
        {
            this.detalles = new HashSet<detalle>();
            this.facturas = new HashSet<factura>();
            this.mesas = new HashSet<mesa>();
            this.olvidos = new HashSet<olvido>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> numact { get; set; }
        public Nullable<bool> activo { get; set; }
        public Nullable<bool> CAMARERO { get; set; }
        public Nullable<bool> COBROCUENTA { get; set; }
        public Nullable<bool> ASEO { get; set; }
        public Nullable<bool> TURNO { get; set; }
        public Nullable<bool> ADMON { get; set; }
        public string CEDULA { get; set; }
        public Nullable<bool> NOMINA { get; set; }
        public string FOTO { get; set; }
        public Nullable<bool> vendePos { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle> detalles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<factura> facturas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mesa> mesas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<olvido> olvidos { get; set; }
    }
}
