//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRoomDig.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonitorPedido
    {
        public int Seccion { get; set; }
        public Nullable<int> CoorX { get; set; }
        public Nullable<int> CoorY { get; set; }
        public Nullable<int> Alto { get; set; }
        public Nullable<int> Ancho { get; set; }
        public Nullable<int> DeAncho { get; set; }
        public Nullable<int> MinsAncho { get; set; }
        public Nullable<int> RangoAncho { get; set; }
        public Nullable<int> CtAncho { get; set; }
        public Nullable<int> ProdAncho { get; set; }
        public Nullable<int> AclaraAncho { get; set; }
        public Nullable<int> OrdenAncho { get; set; }
        public string Font { get; set; }
        public Nullable<decimal> Size { get; set; }
    }
}
