//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRoomDig.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class movhab
    {
        public int id { get; set; }
        public Nullable<int> habini { get; set; }
        public Nullable<int> habfin { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string autoriza { get; set; }
        public Nullable<int> id_causa { get; set; }
        public string nota { get; set; }
        public Nullable<int> tiempo { get; set; }
        public Nullable<decimal> valor { get; set; }
        public Nullable<int> id_pedido { get; set; }
        public Nullable<int> id_atiende { get; set; }
        public string usuario { get; set; }
    }
}
