//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRoomDig.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class movinventario
    {
        public string tipo { get; set; }
        public int identif { get; set; }
        public int item { get; set; }
        public Nullable<int> id_prov { get; set; }
        public Nullable<int> id_bodega_ini { get; set; }
        public Nullable<int> id_bodega_fin { get; set; }
        public Nullable<double> cant { get; set; }
        public Nullable<int> id_producto { get; set; }
        public Nullable<int> id_detmedidas { get; set; }
        public Nullable<decimal> Valor { get; set; }
        public string observa { get; set; }
        public Nullable<int> id_causa { get; set; }
        public Nullable<int> id_conver { get; set; }
        public Nullable<decimal> cantconver { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<decimal> PORCGRAVADO { get; set; }
        public Nullable<decimal> GRAVADO { get; set; }
        public Nullable<System.DateTime> FVENCE { get; set; }
        public string TIPDOCUMENTO { get; set; }
        public string DOCUMENTO { get; set; }
        public Nullable<decimal> DIFERENCIA { get; set; }
        public Nullable<decimal> UTILIDAD { get; set; }
    }
}
