//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRoomDig.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class movinven
    {
        public int id { get; set; }
        public Nullable<int> id_temps { get; set; }
        public Nullable<byte> tipo { get; set; }
        public int id_detmovin { get; set; }
        public int id_bodegas { get; set; }
        public int id_productos { get; set; }
        public Nullable<int> id_detmedidas { get; set; }
        public Nullable<decimal> cantidad { get; set; }
        public Nullable<decimal> valor { get; set; }
        public string observa { get; set; }
        public Nullable<int> id_prove { get; set; }
        public string documento { get; set; }
        public System.DateTime fecha { get; set; }
        public string usuario { get; set; }
        public System.DateTime fec_graba { get; set; }
        public Nullable<int> id_llave1 { get; set; }
        public Nullable<int> id_llave2 { get; set; }
        public Nullable<int> id_llave3 { get; set; }
        public Nullable<decimal> SALDO { get; set; }
        public Nullable<decimal> COSTO { get; set; }
        public Nullable<int> idRecibe { get; set; }
        public Nullable<int> idAreaRecibe { get; set; }
        public Nullable<int> IdMaquina { get; set; }
        public Nullable<int> IdApp { get; set; }
        public Nullable<int> IdPedido { get; set; }
        public Nullable<int> IdMain { get; set; }
    
        public virtual bodega bodega { get; set; }
        public virtual detmedida detmedida { get; set; }
        public virtual detmovin detmovin { get; set; }
        public virtual producto producto { get; set; }
        public virtual temp temp { get; set; }
    }
}
