//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRoomDig.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class msg_institut
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<byte> mes { get; set; }
        public Nullable<bool> print { get; set; }
        public Nullable<bool> pantalla { get; set; }
        public Nullable<bool> activo { get; set; }
    }
}
