//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRoomDig.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mto_prv
    {
        public int id { get; set; }
        public Nullable<bool> hist { get; set; }
        public Nullable<System.DateTime> fecInicio { get; set; }
        public Nullable<System.DateTime> fecFin { get; set; }
        public Nullable<System.DateTime> fecActual { get; set; }
        public Nullable<int> hab { get; set; }
        public int id_clsmto { get; set; }
        public int id_grupo { get; set; }
        public string observa { get; set; }
        public string usuario { get; set; }
        public bool dano { get; set; }
        public string persona { get; set; }
        public Nullable<decimal> valor { get; set; }
        public string notaRepara { get; set; }
        public string usuarioRepara { get; set; }
        public Nullable<System.DateTime> fechaRepara { get; set; }
    }
}
