//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRoomDig.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mtohab
    {
        public int id { get; set; }
        public Nullable<bool> hist { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> hab { get; set; }
        public Nullable<int> id_causa { get; set; }
        public string observa { get; set; }
        public string usuario { get; set; }
        public Nullable<bool> dano { get; set; }
        public string persona { get; set; }
        public Nullable<decimal> valor { get; set; }
        public string reemp { get; set; }
        public string garan { get; set; }
        public string revizo { get; set; }
        public string notaRepara { get; set; }
        public string usuarioRepara { get; set; }
        public Nullable<System.DateTime> fechaRepara { get; set; }
        public Nullable<int> id_seccion { get; set; }
        public Nullable<int> id_grupo { get; set; }
    }
}
