//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRoomDig.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyTecno
    {
        public string id { get; set; }
        public string clave { get; set; }
        public Nullable<int> puntos { get; set; }
        public Nullable<int> cantVisitas { get; set; }
        public System.DateTime fechaActiva { get; set; }
        public Nullable<int> idSegmento { get; set; }
        public Nullable<bool> activa { get; set; }
        public Nullable<decimal> saldo { get; set; }
        public Nullable<int> idCliente { get; set; }
        public string usuario { get; set; }
    
        public virtual segmento segmento { get; set; }
    }
}
