//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRoomDig.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class net
    {
        public int id { get; set; }
        public decimal niva { get; set; }
        public int npedido { get; set; }
        public int nconsumo { get; set; }
        public int nanula { get; set; }
        public Nullable<int> ntrasla { get; set; }
        public Nullable<int> nentr { get; set; }
        public Nullable<int> nbaj { get; set; }
        public Nullable<int> negre { get; set; }
        public Nullable<int> nserv { get; set; }
        public Nullable<int> mensaje { get; set; }
        public Nullable<int> nerror { get; set; }
        public Nullable<int> npend { get; set; }
        public Nullable<int> numabono { get; set; }
        public Nullable<int> ndscto { get; set; }
        public Nullable<int> nvta { get; set; }
        public string prefijo { get; set; }
        public Nullable<int> nout { get; set; }
        public Nullable<int> ndetfac { get; set; }
        public Nullable<short> nmin { get; set; }
        public Nullable<int> ningr { get; set; }
        public Nullable<short> ntos { get; set; }
        public Nullable<int> ncontrol { get; set; }
        public Nullable<int> NCOMANDA { get; set; }
        public Nullable<int> NORDENCOMPRA { get; set; }
        public Nullable<int> NREQUERIRINV { get; set; }
        public Nullable<int> NPROD { get; set; }
        public Nullable<int> NTRANS { get; set; }
        public Nullable<int> nPedPend { get; set; }
        public Nullable<int> nCortesia { get; set; }
        public Nullable<int> tercero { get; set; }
        public Nullable<int> idContrato { get; set; }
        public Nullable<int> Auditor { get; set; }
        public Nullable<int> matProy { get; set; }
        public Nullable<int> reqMat { get; set; }
        public Nullable<int> cotProv { get; set; }
        public Nullable<int> ordCompra { get; set; }
        public Nullable<int> nProducto { get; set; }
    }
}
