//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRoomDig.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class novedadDetalle
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> idNovedad { get; set; }
    
        public virtual novedad novedad { get; set; }
        public virtual novedad novedad1 { get; set; }
        public virtual novedad novedad2 { get; set; }
        public virtual novedad novedad3 { get; set; }
        public virtual novedad novedad4 { get; set; }
        public virtual novedad novedad5 { get; set; }
        public virtual novedad novedad6 { get; set; }
        public virtual novedad novedad7 { get; set; }
        public virtual novedad novedad8 { get; set; }
        public virtual novedad novedad9 { get; set; }
        public virtual novedad novedad10 { get; set; }
        public virtual novedad novedad11 { get; set; }
        public virtual novedad novedad12 { get; set; }
        public virtual novedad novedad13 { get; set; }
        public virtual novedad novedad14 { get; set; }
        public virtual novedad novedad15 { get; set; }
    }
}
