//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRoomDig.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class olvido
    {
        public int id { get; set; }
        public int id_tip_olvido { get; set; }
        public string name { get; set; }
        public int id_est { get; set; }
        public int id_camarera { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> habitacion { get; set; }
    
        public virtual est_olvido est_olvido { get; set; }
        public virtual log_olvido log_olvido { get; set; }
        public virtual mesa mesa { get; set; }
        public virtual mesero mesero { get; set; }
        public virtual TipOlvido TipOlvido { get; set; }
    }
}
