//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRoomDig.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPCclient
    {
        public int NumInterno { get; set; }
        public Nullable<int> id_habita { get; set; }
        public Nullable<int> id_connOpc { get; set; }
        public string varPlcOpc { get; set; }
        public string dirPlcOpc { get; set; }
        public string Descrip { get; set; }
        public Nullable<int> id_device { get; set; }
        public Nullable<bool> valor_BD { get; set; }
        public Nullable<bool> NEGADOR { get; set; }
        public Nullable<int> duracion { get; set; }
    }
}
