//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRoomDig.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class parametros2
    {
        public Nullable<decimal> billete { get; set; }
        public Nullable<int> ceros { get; set; }
        public Nullable<bool> negrilla { get; set; }
        public Nullable<int> espacio { get; set; }
        public Nullable<int> ancho { get; set; }
        public Nullable<int> idprinter { get; set; }
        public string TipLetraNew { get; set; }
        public Nullable<int> TamLetraNew { get; set; }
        public Nullable<System.DateTime> CONTROLTIME { get; set; }
        public Nullable<bool> idpatio { get; set; }
        public Nullable<bool> facturado { get; set; }
        public Nullable<bool> marcar { get; set; }
        public Nullable<int> tiempoReg { get; set; }
        public Nullable<int> TiempoMarca { get; set; }
        public Nullable<bool> CtrPorteria { get; set; }
        public Nullable<bool> ColorSuite { get; set; }
        public Nullable<decimal> CreceX { get; set; }
        public Nullable<bool> CreceNombre { get; set; }
        public Nullable<int> LogoX { get; set; }
        public Nullable<int> LogoY { get; set; }
        public string LogoName { get; set; }
        public Nullable<System.DateTime> Ctrsensor { get; set; }
        public string CtoPark { get; set; }
        public Nullable<int> Barra { get; set; }
        public Nullable<int> TiempoLimpia { get; set; }
        public Nullable<bool> PedBar { get; set; }
        public Nullable<bool> GRABACOMM { get; set; }
        public string VIDEODEFAPAN1 { get; set; }
        public string VIDEODEFAPAN2 { get; set; }
        public Nullable<bool> REGGARAJE { get; set; }
        public Nullable<bool> PULFACT { get; set; }
        public Nullable<bool> SERVAUTOM { get; set; }
        public Nullable<bool> VERPLACAS { get; set; }
        public Nullable<bool> PRINTVOLANTE { get; set; }
        public Nullable<bool> PRINTCUENTA { get; set; }
        public Nullable<bool> COPYFACT { get; set; }
        public Nullable<int> SALESURTIR { get; set; }
        public Nullable<bool> SALEVOLANTE { get; set; }
        public Nullable<int> CODCLIENTE { get; set; }
        public string CCOPIA { get; set; }
        public Nullable<bool> INDIVATIENDE { get; set; }
        public Nullable<bool> TIMESCALA { get; set; }
        public Nullable<int> OpcPlano { get; set; }
        public Nullable<int> ID_RESOLUCION { get; set; }
        public Nullable<int> COBROPARK { get; set; }
        public Nullable<int> TIPOFACTURA { get; set; }
        public Nullable<bool> ORDENC { get; set; }
        public Nullable<bool> POS { get; set; }
        public Nullable<bool> verProductoventa { get; set; }
        public Nullable<int> ID_FIDELIZACION { get; set; }
        public Nullable<int> cantTagsXGrupo { get; set; }
        public Nullable<bool> OPCCliente { get; set; }
        public Nullable<bool> POSantiguo { get; set; }
        public Nullable<bool> SINLINEAS { get; set; }
        public Nullable<bool> defaAllInc { get; set; }
        public Nullable<bool> defaAllInc1 { get; set; }
        public Nullable<bool> defaAllInc2 { get; set; }
        public Nullable<bool> defaAllInc3 { get; set; }
        public Nullable<bool> defaAllInc4 { get; set; }
        public Nullable<bool> defaAllInc5 { get; set; }
        public string CONTABILIDAD { get; set; }
        public string cashPortName { get; set; }
        public Nullable<decimal> RETEFUENTE { get; set; }
        public Nullable<decimal> RETEIVA { get; set; }
        public Nullable<decimal> RETEICA { get; set; }
        public Nullable<int> RETEIVA_IDTIPO { get; set; }
        public Nullable<decimal> BASERETEFUENTE { get; set; }
        public Nullable<bool> IDTERCERO { get; set; }
        public Nullable<bool> CashDispenser { get; set; }
        public Nullable<bool> COBROCAMBHAB { get; set; }
        public Nullable<int> izqComandaCocina { get; set; }
        public Nullable<bool> notVerStock { get; set; }
        public string pathPlano { get; set; }
        public Nullable<int> timePulsaChapa { get; set; }
        public Nullable<int> timePulsaChapaIn { get; set; }
        public Nullable<decimal> BASERETEICA { get; set; }
        public int id { get; set; }
        public string infoSoftware1 { get; set; }
        public string infoSoftware2 { get; set; }
        public string infoCopyRight { get; set; }
        public string infoVenta { get; set; }
    }
}
