//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRoomDig.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class parametros3
    {
        public int id { get; set; }
        public Nullable<int> codeAlimentacion { get; set; }
        public Nullable<decimal> PORCCREE { get; set; }
        public string sqlFecha { get; set; }
        public Nullable<bool> winSpa { get; set; }
        public Nullable<bool> TiqueteEntrega { get; set; }
        public Nullable<int> talanqueraIn { get; set; }
        public Nullable<int> talanqueraOut { get; set; }
        public Nullable<int> nameVideoCash { get; set; }
        public Nullable<int> TopVideoIn { get; set; }
        public Nullable<int> leftVideoIn { get; set; }
        public Nullable<bool> borraSv { get; set; }
        public Nullable<bool> compDianImpto { get; set; }
        public string OrderInven { get; set; }
        public Nullable<bool> borraSavePer { get; set; }
        public Nullable<decimal> prodAdulAdic { get; set; }
        public Nullable<decimal> prodNinoAdic { get; set; }
        public Nullable<int> horaCheckOut { get; set; }
        public Nullable<int> minCheckOut { get; set; }
        public string pathReportes { get; set; }
        public Nullable<int> ParAlertaCierre { get; set; }
        public Nullable<int> ParAlertaFactura { get; set; }
        public Nullable<bool> reporteHabSinReg { get; set; }
        public Nullable<bool> grabadoHabSinReg { get; set; }
        public Nullable<bool> noRepoMto { get; set; }
        public Nullable<bool> cobroInicialAutom { get; set; }
        public Nullable<bool> modPedidoTicket { get; set; }
        public Nullable<int> cantDecimalPlano { get; set; }
        public Nullable<int> tmrMensaje { get; set; }
        public Nullable<int> tmrCasilla { get; set; }
        public Nullable<int> tmrEmail { get; set; }
        public string mensCuenta1 { get; set; }
        public string mensCuenta2 { get; set; }
        public string descripHotel { get; set; }
        public Nullable<bool> siReservaCruzada { get; set; }
        public Nullable<int> truncaPago { get; set; }
        public Nullable<bool> dsctoComercial { get; set; }
        public string OpcPathApp { get; set; }
        public Nullable<bool> validaClave { get; set; }
        public Nullable<bool> inProduccion { get; set; }
        public Nullable<int> ParAlertaFacturaCamar { get; set; }
        public Nullable<int> ParTiempoAbrirOut { get; set; }
        public Nullable<bool> abreGarajeRegistrada { get; set; }
        public Nullable<int> ParTiempoAlertaLuz { get; set; }
        public Nullable<int> ParSegAlertaFacturaCamar { get; set; }
        public Nullable<bool> verAhorroFact { get; set; }
        public Nullable<bool> kRoom { get; set; }
        public Nullable<bool> kLin { get; set; }
        public Nullable<bool> isReqSuperv { get; set; }
        public Nullable<bool> ImprimeBaucher { get; set; }
        public Nullable<int> pCOutB { get; set; }
        public Nullable<int> pCOutM { get; set; }
        public Nullable<int> pCOutA { get; set; }
        public Nullable<int> sensor2 { get; set; }
        public Nullable<int> diasResolucion { get; set; }
        public Nullable<int> facturasResolucion { get; set; }
        public Nullable<bool> minibar { get; set; }
        public string cierreExt { get; set; }
        public Nullable<bool> kService { get; set; }
        public Nullable<int> minSaleHabDespFact { get; set; }
        public Nullable<int> servExcentSalida { get; set; }
        public string tcpHost { get; set; }
        public Nullable<int> serverPuerto { get; set; }
        public Nullable<int> serverFamily { get; set; }
        public string garantia { get; set; }
        public string politicas { get; set; }
        public string infAdicional { get; set; }
        public string espacios { get; set; }
        public string detSolicitudCot { get; set; }
        public string detOC { get; set; }
        public string det2OC { get; set; }
        public Nullable<int> TimeService { get; set; }
        public string AdminCard { get; set; }
        public string MyCashPrinter { get; set; }
        public string SetupPrint { get; set; }
        public Nullable<int> AlterPort { get; set; }
        public Nullable<int> serverFamily2 { get; set; }
        public Nullable<bool> isEnableMyCash { get; set; }
        public Nullable<bool> siTicketEntrega { get; set; }
        public Nullable<bool> informeCaja { get; set; }
        public Nullable<bool> dividirAbono { get; set; }
        public Nullable<int> siNegativoStock { get; set; }
        public string AlterPrinter { get; set; }
        public Nullable<bool> UseMyCash { get; set; }
        public Nullable<bool> IsHotel { get; set; }
        public Nullable<bool> IsSpa { get; set; }
        public Nullable<System.DateTime> nfecdian2 { get; set; }
        public Nullable<bool> siSaleMesaFactura { get; set; }
        public Nullable<int> AltoFilaPedidoPos { get; set; }
        public string ContextoSitio { get; set; }
    }
}
