//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRoomDig.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class parametro
    {
        public int id { get; set; }
        public string UsrRazon { get; set; }
        public string UsrNit { get; set; }
        public string nrespon { get; set; }
        public Nullable<byte> UsrDigNit { get; set; }
        public string UsrDirFis { get; set; }
        public Nullable<byte> UsrCal { get; set; }
        public string SofCodProv { get; set; }
        public Nullable<int> SofNum { get; set; }
        public string SofNumLic { get; set; }
        public string nica { get; set; }
        public string ncontrib { get; set; }
        public decimal niva { get; set; }
        public System.DateTime nfecdian { get; set; }
        public string nfiva { get; set; }
        public string ndian { get; set; }
        public string nautoriza { get; set; }
        public int npedido { get; set; }
        public int nconsumo { get; set; }
        public int nanula { get; set; }
        public short nnos { get; set; }
        public Nullable<int> nres { get; set; }
        public Nullable<int> ntrasla { get; set; }
        public Nullable<int> nentr { get; set; }
        public Nullable<int> nbaj { get; set; }
        public Nullable<int> negre { get; set; }
        public Nullable<int> ningr { get; set; }
        public Nullable<int> nprop { get; set; }
        public Nullable<int> nserv { get; set; }
        public Nullable<int> mensaje { get; set; }
        public Nullable<int> nerror { get; set; }
        public Nullable<int> npend { get; set; }
        public Nullable<short> ntos { get; set; }
        public Nullable<int> numabono { get; set; }
        public Nullable<int> ndscto { get; set; }
        public Nullable<int> nvta { get; set; }
        public string prefijo { get; set; }
        public Nullable<int> nout { get; set; }
        public Nullable<int> ndetfac { get; set; }
        public Nullable<short> nmin { get; set; }
        public Nullable<int> tempo { get; set; }
        public Nullable<bool> FactCabeLoop { get; set; }
        public Nullable<int> npdian { get; set; }
        public Nullable<int> ndano { get; set; }
        public Nullable<bool> nfact { get; set; }
        public Nullable<bool> ncoma { get; set; }
        public Nullable<bool> ncontraFac { get; set; }
        public Nullable<bool> ncontraCta { get; set; }
        public Nullable<bool> ngrupFac { get; set; }
        public Nullable<int> nlinea { get; set; }
        public Nullable<bool> Facturar { get; set; }
        public Nullable<decimal> porcprop { get; set; }
        public Nullable<decimal> dscto { get; set; }
        public Nullable<bool> autoconver { get; set; }
        public Nullable<bool> pisoini { get; set; }
        public Nullable<int> lugar { get; set; }
        public Nullable<int> comanda { get; set; }
        public Nullable<int> cantdefa { get; set; }
        public Nullable<int> proddefa { get; set; }
        public Nullable<int> meddefa { get; set; }
        public Nullable<int> altcantdefa { get; set; }
        public Nullable<int> altproddefa { get; set; }
        public Nullable<int> altmeddefa { get; set; }
        public Nullable<int> naviz { get; set; }
        public Nullable<bool> Excedente { get; set; }
        public Nullable<bool> ClaveExc { get; set; }
        public Nullable<bool> AumPrecio { get; set; }
        public Nullable<bool> nSeguro { get; set; }
        public Nullable<bool> SeguroTotal { get; set; }
        public Nullable<bool> SeguroModif { get; set; }
        public Nullable<int> cantpend { get; set; }
        public Nullable<bool> HabTemporal { get; set; }
        public Nullable<bool> TimeFree { get; set; }
        public Nullable<bool> SinLugar { get; set; }
        public Nullable<bool> exgid { get; set; }
        public Nullable<bool> SinComanda { get; set; }
        public Nullable<bool> SinMesero { get; set; }
        public string menfact { get; set; }
        public string menfact1 { get; set; }
        public string menfact2 { get; set; }
        public string menfact3 { get; set; }
        public string menfact4 { get; set; }
        public Nullable<bool> menale { get; set; }
        public Nullable<int> sublines { get; set; }
        public Nullable<bool> horsale { get; set; }
        public Nullable<int> graliva { get; set; }
        public Nullable<int> HabAlto { get; set; }
        public Nullable<int> HabAncho { get; set; }
        public Nullable<int> HabLetra { get; set; }
        public Nullable<int> HabMto { get; set; }
        public Nullable<int> HabCir { get; set; }
        public Nullable<int> hasta { get; set; }
        public Nullable<int> colfecha { get; set; }
        public Nullable<int> colfacts { get; set; }
        public string admin { get; set; }
        public string TipLetraGra { get; set; }
        public Nullable<int> TamLetraGra { get; set; }
        public string TipLetraPeq { get; set; }
        public Nullable<int> TamLetraPeq { get; set; }
        public Nullable<bool> CtrlRadio { get; set; }
        public Nullable<System.DateTime> FecCantPend { get; set; }
        public string ndirc { get; set; }
        public string ntelf { get; set; }
        public string UsrRazon2 { get; set; }
        public Nullable<bool> anexo { get; set; }
        public Nullable<int> Cod_Hotel { get; set; }
        public Nullable<int> Cod_Ciudad { get; set; }
        public Nullable<bool> nSalidaPrint { get; set; }
        public Nullable<bool> nfact2 { get; set; }
        public Nullable<int> cod_pais { get; set; }
        public Nullable<bool> ConsReserva { get; set; }
        public Nullable<bool> Tecno { get; set; }
        public Nullable<bool> siPermisos { get; set; }
        public Nullable<System.DateTime> nfecdian2 { get; set; }
    }
}
