//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRoomDig.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pedidos_detalle
    {
        public int id_pedidos { get; set; }
        public int item { get; set; }
        public Nullable<int> hab { get; set; }
        public Nullable<int> cant { get; set; }
        public Nullable<int> id_tipoHuesped { get; set; }
        public Nullable<decimal> vl_pax { get; set; }
        public Nullable<int> id_promoc { get; set; }
        public Nullable<decimal> vl_dscto { get; set; }
        public Nullable<bool> SegHotel { get; set; }
        public Nullable<bool> AllInc { get; set; }
        public Nullable<bool> Desy { get; set; }
        public Nullable<bool> R1 { get; set; }
        public Nullable<bool> Alm { get; set; }
        public Nullable<bool> R2 { get; set; }
        public Nullable<bool> Cen { get; set; }
    }
}
