//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRoomDig.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PEDIDOS_COBROS
    {
        public int ID_PEDIDOS { get; set; }
        public int ITEM { get; set; }
        public Nullable<int> CANTIDAD { get; set; }
        public Nullable<int> ID_PRODUCTOS { get; set; }
        public Nullable<int> ID_DETMEDIDAS { get; set; }
        public Nullable<decimal> TARIFA { get; set; }
        public Nullable<int> ID_TIPIVA { get; set; }
        public Nullable<decimal> VL_TARIVA { get; set; }
    }
}
