//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRoomDig.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pedido
    {
        public int id { get; set; }
        public int id_mesas { get; set; }
        public int id_detestados { get; set; }
        public string usuario { get; set; }
        public System.DateTime fec_graba { get; set; }
        public Nullable<System.DateTime> fec_sale { get; set; }
        public Nullable<System.DateTime> fec_cobra { get; set; }
        public Nullable<System.DateTime> fec_final { get; set; }
        public Nullable<System.DateTime> fec_real { get; set; }
        public string identifica { get; set; }
        public string carnet { get; set; }
        public Nullable<int> traslado { get; set; }
        public Nullable<bool> temporal { get; set; }
        public Nullable<int> adultos { get; set; }
        public Nullable<int> niños { get; set; }
        public Nullable<int> permanencia { get; set; }
        public Nullable<int> tipoperma { get; set; }
        public Nullable<int> id_motivos { get; set; }
        public Nullable<int> id_procede { get; set; }
        public Nullable<int> id_destino { get; set; }
        public Nullable<int> regalo { get; set; }
        public Nullable<int> CONTROL { get; set; }
        public string usuario_entrega { get; set; }
        public Nullable<System.DateTime> arreglada { get; set; }
        public Nullable<int> id_mesero { get; set; }
        public Nullable<int> Id_Maquina { get; set; }
        public Nullable<int> Comanda { get; set; }
        public Nullable<int> Id_reserva { get; set; }
        public Nullable<int> Bebes { get; set; }
        public Nullable<int> Id_suites { get; set; }
        public Nullable<System.DateTime> FEC_CUENTA { get; set; }
        public Nullable<System.DateTime> FEC_FACTURA { get; set; }
        public Nullable<int> ID_VENDEDOR { get; set; }
        public Nullable<int> ID_TIPOCAR { get; set; }
        public Nullable<int> ID_TEMPO { get; set; }
        public Nullable<int> ID_PLAN { get; set; }
        public Nullable<int> ID_LISTAS { get; set; }
        public Nullable<int> id_acomodacion { get; set; }
        public Nullable<int> id_origen { get; set; }
        public Nullable<int> id_tipoReserva { get; set; }
        public Nullable<int> id_transporte { get; set; }
        public Nullable<bool> equipaje { get; set; }
        public Nullable<bool> ocultaTarifa { get; set; }
        public int id_folio { get; set; }
        public string descripcion { get; set; }
        public Nullable<decimal> tarifa { get; set; }
        public Nullable<int> idTercero { get; set; }
        public Nullable<int> idPago { get; set; }
        public Nullable<int> idTarifa { get; set; }
        public string acuerdos { get; set; }
        public Nullable<int> idTipRegistro { get; set; }
        public string habFolioAdd { get; set; }
        public Nullable<int> habMain { get; set; }
        public Nullable<int> IdApp { get; set; }
    
        public virtual detestado detestado { get; set; }
    }
}
