//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRoomDig.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pedidos_auditoria
    {
        public int id_pedido { get; set; }
        public int consec { get; set; }
        public Nullable<bool> inicial { get; set; }
        public Nullable<int> id_tiposer { get; set; }
        public Nullable<int> id_clases { get; set; }
        public Nullable<decimal> valor { get; set; }
        public Nullable<decimal> vl_tariva { get; set; }
        public Nullable<int> id_tariva { get; set; }
        public Nullable<int> tiempo { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<int> adultos { get; set; }
        public Nullable<int> ninos { get; set; }
        public Nullable<decimal> costo { get; set; }
        public Nullable<int> ID_PRODUCTOS { get; set; }
        public Nullable<int> ID_CANT { get; set; }
        public Nullable<int> ID_PLAN { get; set; }
        public Nullable<int> ID_ACOMODACION { get; set; }
    }
}
