//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRoomDig.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PedidosPendDet
    {
        public int id_PedidosPendDetMst { get; set; }
        public int item { get; set; }
        public Nullable<decimal> lPosCant { get; set; }
        public Nullable<int> lPosPlu { get; set; }
        public Nullable<decimal> Tarifa { get; set; }
        public string Observa { get; set; }
        public Nullable<decimal> Impto { get; set; }
        public Nullable<int> lTipImpto { get; set; }
        public Nullable<decimal> PrecioReal { get; set; }
        public Nullable<int> lAtiende { get; set; }
    }
}
