//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRoomDig.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class periodo
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<bool> usuario { get; set; }
        public Nullable<bool> condicion { get; set; }
        public Nullable<int> id_funciones { get; set; }
        public Nullable<int> control { get; set; }
        public Nullable<int> seguridad { get; set; }
        public Nullable<int> id_bodega { get; set; }
        public Nullable<bool> generals { get; set; }
        public Nullable<bool> contable { get; set; }
        public Nullable<bool> pagos { get; set; }
        public Nullable<bool> camareros { get; set; }
        public string CD { get; set; }
        public Nullable<bool> CierreAutom { get; set; }
    }
}
