//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRoomDig.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pista
    {
        public int id { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string usuario { get; set; }
        public string autoriza { get; set; }
        public string descripcion { get; set; }
        public Nullable<bool> temporal { get; set; }
        public Nullable<bool> acceso { get; set; }
        public Nullable<byte> nivel { get; set; }
        public Nullable<int> id_clasepista { get; set; }
        public string administrador { get; set; }
        public Nullable<bool> marcar { get; set; }
    }
}
