//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRoomDig.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class plantPlanoDet
    {
        public int id_plantPlano { get; set; }
        public int id_etapa { get; set; }
        public int item { get; set; }
        public Nullable<int> tamano { get; set; }
        public string JustificaChar { get; set; }
        public string rotuloFijoShow { get; set; }
        public string campoShow { get; set; }
        public Nullable<int> numCaracterShow { get; set; }
        public string formatoDatoShow { get; set; }
        public Nullable<int> numDecimales { get; set; }
    }
}
