//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRoomDig.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class plantilla_prods
    {
        public int id_plantilla { get; set; }
        public int id_productos { get; set; }
        public int id_detmedidas { get; set; }
        public Nullable<int> cant { get; set; }
        public Nullable<int> id_bodegas { get; set; }
    }
}
