//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRoomDig.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLANTILLA_DETRI
    {
        public int ID_PLANTILLA_RI { get; set; }
        public int ITEM { get; set; }
        public Nullable<decimal> CANTIDAD { get; set; }
        public Nullable<int> ID_PRODUCTO { get; set; }
    }
}
