//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRoomDig.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLANTILLA_RI
    {
        public int ID_PLANTILLA_RI { get; set; }
        public string NAME { get; set; }
        public Nullable<int> ID_CENTROC { get; set; }
        public Nullable<int> TIEMPOPARA { get; set; }
        public Nullable<int> ID_TIEMPO_RI { get; set; }
        public Nullable<int> ID_USUARIO { get; set; }
    }
}
