//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRoomDig.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class plantPlanoEtapa
    {
        public int id_plantPlano { get; set; }
        public int id_etapa { get; set; }
        public string sqlshow { get; set; }
        public string descrip { get; set; }
        public string campoSuma { get; set; }
        public Nullable<bool> ingreso { get; set; }
    }
}
