//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRoomDig.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class plantPLano
    {
        public int id { get; set; }
        public string name { get; set; }
        public string fileName { get; set; }
        public string path { get; set; }
        public string delimiter { get; set; }
        public Nullable<bool> cicloParam { get; set; }
        public string campoSi { get; set; }
        public string valorSi { get; set; }
        public string PARAM1 { get; set; }
        public string PARAM2 { get; set; }
        public string PARAM3 { get; set; }
        public string PARAM4 { get; set; }
        public string PARAM5 { get; set; }
        public string nombrePUC { get; set; }
        public string naturalPUC { get; set; }
        public string bases { get; set; }
        public string concepto { get; set; }
        public string identifica { get; set; }
        public Nullable<bool> noCree { get; set; }
    }
}
