//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRoomDig.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class plaporteria
    {
        public int numconsec { get; set; }
        public string placa { get; set; }
        public Nullable<System.DateTime> fecha_graba { get; set; }
        public string portero_graba { get; set; }
        public Nullable<System.DateTime> fecha_salida { get; set; }
        public string portero_salida { get; set; }
        public Nullable<int> clase { get; set; }
        public string nota { get; set; }
        public Nullable<System.DateTime> fecha_nota { get; set; }
        public string usuario { get; set; }
        public Nullable<int> id_pedidos { get; set; }
    }
}
