//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRoomDig.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public producto()
        {
            this.alquilers = new HashSet<alquiler>();
            this.detalles = new HashSet<detalle>();
            this.formulas = new HashSet<formula>();
            this.movinvens = new HashSet<movinven>();
            this.promsprods = new HashSet<promsprod>();
            this.stocks = new HashSet<stock>();
            this.trfaprods = new HashSet<trfaprod>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> minimo { get; set; }
        public Nullable<int> promedio { get; set; }
        public Nullable<int> maximo { get; set; }
        public string abre { get; set; }
        public Nullable<int> id_clase { get; set; }
        public Nullable<int> id_clsmedidas { get; set; }
        public Nullable<int> id_frmshow { get; set; }
        public string descrip { get; set; }
        public Nullable<bool> formula { get; set; }
        public Nullable<bool> venta { get; set; }
        public Nullable<bool> inventario { get; set; }
        public Nullable<bool> intangible { get; set; }
        public Nullable<bool> inicial { get; set; }
        public Nullable<bool> temporal { get; set; }
        public Nullable<decimal> seguro { get; set; }
        public Nullable<int> id_orden { get; set; }
        public Nullable<int> tiempo { get; set; }
        public Nullable<bool> NoCobroCero { get; set; }
        public Nullable<int> id_bodegas { get; set; }
        public Nullable<bool> Inactivo { get; set; }
        public Nullable<decimal> COMPGRAVA { get; set; }
        public string BARRAS { get; set; }
        public string PUC { get; set; }
        public string REF { get; set; }
        public Nullable<int> PRESMEDIDA { get; set; }
        public Nullable<decimal> PRESCANTIDAD { get; set; }
        public Nullable<decimal> COSTO_UNIT { get; set; }
        public Nullable<int> MED_SUGER { get; set; }
        public Nullable<int> PUNTOS { get; set; }
        public string MARCA { get; set; }
        public string TALLA { get; set; }
        public string COLOR { get; set; }
        public string UBICACIoN { get; set; }
        public Nullable<decimal> IMPOCONSUMO { get; set; }
        public string FOTO { get; set; }
        public Nullable<bool> DIASOL { get; set; }
        public Nullable<bool> SCANPROD { get; set; }
        public Nullable<int> idCentroC { get; set; }
        public string Serial { get; set; }
        public byte[] Imagen { get; set; }
        public Nullable<int> tipo_activo { get; set; }
        public Nullable<bool> siPrestamo { get; set; }
        public Nullable<int> idControl { get; set; }
        public Nullable<bool> valDefecto { get; set; }
        public bool favorito { get; set; }
        public Nullable<decimal> cantUndEmpaque { get; set; }
        public string UndEmpaque { get; set; }
        public Nullable<decimal> maxTras { get; set; }
        public Nullable<decimal> minTras { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<alquiler> alquilers { get; set; }
        public virtual clas clas { get; set; }
        public virtual clsmedida clsmedida { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle> detalles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<formula> formulas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<movinven> movinvens { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<promsprod> promsprods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<stock> stocks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trfaprod> trfaprods { get; set; }
    }
}
