//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRoomDig.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class promMyTecno
    {
        public int id { get; set; }
        public string descripcion { get; set; }
        public int dia { get; set; }
        public Nullable<int> horaIni { get; set; }
        public Nullable<int> horaFin { get; set; }
        public int idSegmento { get; set; }
        public Nullable<decimal> dscto { get; set; }
        public Nullable<bool> activo { get; set; }
        public byte[] imagen { get; set; }
        public string color { get; set; }
        public Nullable<int> puntos { get; set; }
    }
}
