//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRoomDig.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROMOCIONAL
    {
        public int ID_ORIGEN { get; set; }
        public int ID_PROMOCIONAL { get; set; }
        public string CODE { get; set; }
        public string NAME { get; set; }
        public Nullable<decimal> PORCENTAJE { get; set; }
        public Nullable<bool> DEFECTO { get; set; }
        public Nullable<bool> ACTIVO { get; set; }
        public string USUARIO { get; set; }
        public Nullable<System.DateTime> FECHA_GRABA { get; set; }
        public Nullable<bool> PVP { get; set; }
    }
}
