//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRoomDig.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class promssecc
    {
        public int id_proms { get; set; }
        public int id_secciones { get; set; }
        public Nullable<int> cantidad { get; set; }
    
        public virtual prom prom { get; set; }
        public virtual seccione seccione { get; set; }
    }
}
