//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRoomDig.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class promsfree
    {
        public int id_proms { get; set; }
        public int item { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<int> id_productos { get; set; }
        public Nullable<int> id_detmedidas { get; set; }
        public Nullable<decimal> dscto { get; set; }
        public Nullable<bool> pendiente { get; set; }
        public Nullable<int> clase { get; set; }
        public Nullable<int> grupo { get; set; }
        public Nullable<int> seccion { get; set; }
        public Nullable<int> indicador { get; set; }
        public Nullable<int> dia { get; set; }
        public string desde { get; set; }
        public string hasta { get; set; }
    }
}
