//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRoomDig.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class proveedor
    {
        public int id { get; set; }
        public string name { get; set; }
        public string nit { get; set; }
        public string direccion { get; set; }
        public string telefono { get; set; }
        public string fax { get; set; }
        public string contacto { get; set; }
        public Nullable<int> id_clasif { get; set; }
        public Nullable<int> puntaje { get; set; }
        public Nullable<System.DateTime> fec_actual { get; set; }
        public string usuario { get; set; }
        public System.DateTime fec_graba { get; set; }
        public string observa { get; set; }
        public Nullable<bool> activo { get; set; }
        public Nullable<int> ID_CIUDAD { get; set; }
        public string EMAIL { get; set; }
        public Nullable<int> idRegimen { get; set; }
    }
}
