//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRoomDig.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class recupera_cartera
    {
        public int id { get; set; }
        public string prefijo { get; set; }
        public Nullable<int> id_facturas { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string usuario { get; set; }
        public Nullable<decimal> monto { get; set; }
        public Nullable<decimal> saldo { get; set; }
        public string DESCRIPCION { get; set; }
    }
}
