//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRoomDig.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RepCamareria
    {
        public int id { get; set; }
        public Nullable<int> id_mesas { get; set; }
        public Nullable<int> id_pedidos { get; set; }
        public Nullable<int> id_atiende { get; set; }
        public Nullable<System.DateTime> fec_salida { get; set; }
        public Nullable<System.DateTime> fecha_In { get; set; }
        public Nullable<System.DateTime> Fecha_out { get; set; }
        public Nullable<int> tmmin { get; set; }
        public Nullable<bool> SinRep { get; set; }
        public Nullable<int> id_tipo { get; set; }
    }
}
