//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRoomDig.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class reserva
    {
        public int id { get; set; }
        public Nullable<int> id_estreserva { get; set; }
        public Nullable<int> id_pedidos { get; set; }
        public Nullable<System.DateTime> fec_graba { get; set; }
        public Nullable<System.DateTime> fec_cruza { get; set; }
        public string usuario_graba { get; set; }
        public string usuario_cruza { get; set; }
        public Nullable<int> id_factura { get; set; }
        public Nullable<int> id_motivos { get; set; }
        public Nullable<decimal> valor { get; set; }
        public string email { get; set; }
        public string fax { get; set; }
        public Nullable<int> adultos { get; set; }
        public Nullable<int> ninos { get; set; }
        public Nullable<bool> resalta { get; set; }
        public string nombre { get; set; }
        public Nullable<System.DateTime> desde { get; set; }
        public Nullable<System.DateTime> hasta { get; set; }
        public string Contacto { get; set; }
        public string nota { get; set; }
        public string acuerdos { get; set; }
        public string gustos { get; set; }
        public Nullable<int> id_suites { get; set; }
        public string Identifica { get; set; }
        public Nullable<int> Documento { get; set; }
        public string CODERESERVA { get; set; }
        public Nullable<bool> empresa { get; set; }
        public Nullable<int> ID_AGENCIAS { get; set; }
        public Nullable<int> ID_LISTAS { get; set; }
        public Nullable<int> Id_Acomodacion { get; set; }
        public Nullable<decimal> @base { get; set; }
        public Nullable<bool> iva { get; set; }
        public Nullable<int> Id_plan { get; set; }
        public Nullable<System.DateTime> FECHA_ANULA { get; set; }
        public Nullable<decimal> tarifa { get; set; }
        public Nullable<int> PAX { get; set; }
        public Nullable<decimal> porcImpto { get; set; }
        public Nullable<int> bebes { get; set; }
        public Nullable<int> idTercero { get; set; }
        public string primname { get; set; }
        public string segname { get; set; }
        public string primapel { get; set; }
        public string segapel { get; set; }
        public Nullable<System.DateTime> plazo { get; set; }
        public string REFERENCIA { get; set; }
        public Nullable<decimal> Comision { get; set; }
        public Nullable<int> idCondicion { get; set; }
        public string PROMOCIONAL { get; set; }
        public Nullable<int> idPais { get; set; }
        public Nullable<int> Habs { get; set; }
        public Nullable<bool> decoracion { get; set; }
    }
}
