//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRoomDig.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SENSOR
    {
        public int AUT { get; set; }
        public Nullable<int> hab { get; set; }
        public Nullable<System.DateTime> fecini { get; set; }
        public Nullable<System.DateTime> fecfin { get; set; }
        public Nullable<int> tiempo { get; set; }
        public Nullable<int> id_pedidos { get; set; }
        public string tiempotx { get; set; }
        public string TURNO { get; set; }
        public Nullable<System.DateTime> ANTABIERTA { get; set; }
        public string TXABIERTA { get; set; }
    }
}
