//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRoomDig.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class setup_taxis
    {
        public Nullable<decimal> Monto { get; set; }
        public Nullable<bool> Modificar { get; set; }
        public Nullable<bool> valor { get; set; }
        public Nullable<bool> placa { get; set; }
        public Nullable<bool> hab { get; set; }
        public Nullable<bool> nombre { get; set; }
        public Nullable<bool> empresa { get; set; }
        public Nullable<bool> telefono { get; set; }
        public Nullable<bool> imprime { get; set; }
        public Nullable<int> ctrTimeTaxi { get; set; }
        public Nullable<int> DiasVenceTicket { get; set; }
        public int id { get; set; }
        public Nullable<decimal> monto2 { get; set; }
    }
}
