//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRoomDig.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sostenibilidad
    {
        public int id { get; set; }
        public string empresa { get; set; }
        public Nullable<double> VMision { get; set; }
        public string mision { get; set; }
        public Nullable<double> VVision { get; set; }
        public string vision { get; set; }
        public Nullable<double> VPolitica { get; set; }
        public string polCalidad { get; set; }
        public Nullable<System.DateTime> fechaGraba { get; set; }
        public Nullable<System.DateTime> fechaActualiza { get; set; }
        public string detalleModif { get; set; }
    }
}
