//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRoomDig.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class stockMinimo
    {
        public int idProducto { get; set; }
        public int idBodega { get; set; }
        public Nullable<bool> isAutomRequis { get; set; }
        public Nullable<decimal> stockMinimo1 { get; set; }
        public Nullable<decimal> cantRequer { get; set; }
    }
}
