//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRoomDig.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class suite
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public suite()
        {
            this.alquilers = new HashSet<alquiler>();
            this.mesas = new HashSet<mesa>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string descrip { get; set; }
        public Nullable<int> color { get; set; }
        public Nullable<int> id_productos { get; set; }
        public Nullable<int> id_detmedidas { get; set; }
        public Nullable<int> avizar { get; set; }
        public Nullable<int> anter { get; set; }
        public Nullable<int> limpia { get; set; }
        public string CD { get; set; }
        public string PUC { get; set; }
        public Nullable<decimal> tribut { get; set; }
        public string VIDEO { get; set; }
        public Nullable<int> KPI { get; set; }
        public Nullable<int> DSCTOPUC { get; set; }
        public string nameAlt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<alquiler> alquilers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mesa> mesas { get; set; }
    }
}
