//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRoomDig.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class supervision
    {
        public int id { get; set; }
        public int id_Mesa { get; set; }
        public string supervisa { get; set; }
        public System.DateTime fec_Supervisa { get; set; }
        public string observa { get; set; }
        public Nullable<bool> apta { get; set; }
    }
}
