//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRoomDig.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tablatemporada
    {
        public int consec { get; set; }
        public string hora { get; set; }
        public Nullable<int> dias { get; set; }
        public Nullable<int> siguiente { get; set; }
        public string observa { get; set; }
        public Nullable<int> temporada { get; set; }
    }
}
