//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRoomDig.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TANQAGUAINFO
    {
        public int AUTOM { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public string HORAINICIO { get; set; }
        public string HORAFIN { get; set; }
        public Nullable<int> LECTURA { get; set; }
        public Nullable<int> CONSUMO { get; set; }
        public Nullable<decimal> FTELECCLOR { get; set; }
        public Nullable<decimal> FTELECPH { get; set; }
        public Nullable<decimal> FTEDOSCLOR { get; set; }
        public Nullable<decimal> FTEDOSELEV { get; set; }
        public Nullable<decimal> TAQLECCLOR { get; set; }
        public Nullable<decimal> TAQLECPH { get; set; }
        public Nullable<decimal> TAQDOSCLOR { get; set; }
        public Nullable<decimal> DUREZA { get; set; }
        public Nullable<decimal> SALES { get; set; }
        public string OPERADOR { get; set; }
        public string REVIZA { get; set; }
        public string USUARIO { get; set; }
        public Nullable<int> MAQUINA { get; set; }
    }
}
