//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRoomDig.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tarjetasDispo
    {
        public int consec { get; set; }
        public string id { get; set; }
        public bool asignada { get; set; }
        public Nullable<bool> recarga { get; set; }
        public Nullable<decimal> saldo { get; set; }
    }
}
