//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRoomDig.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class test_OnOff
    {
        public int consec { get; set; }
        public Nullable<int> id_Habita { get; set; }
        public Nullable<int> id_dispo { get; set; }
        public Nullable<bool> activo { get; set; }
        public Nullable<int> indice { get; set; }
        public Nullable<System.DateTime> fechaIni { get; set; }
        public Nullable<System.DateTime> fechaFin { get; set; }
    }
}
