//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRoomDig.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipiva
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<bool> ver { get; set; }
        public Nullable<bool> seguro { get; set; }
        public Nullable<bool> noBase { get; set; }
        public Nullable<decimal> porc { get; set; }
        public string PUC { get; set; }
        public string DESCRIP { get; set; }
        public Nullable<decimal> TRIBUT { get; set; }
        public Nullable<bool> AUTOR { get; set; }
        public Nullable<int> CONTRAPUC { get; set; }
        public Nullable<bool> defecto { get; set; }
    }
}
