//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRoomDig.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipoProdDscto
    {
        public int OrdenReg { get; set; }
        public string tipoProd { get; set; }
        public string signo { get; set; }
        public Nullable<decimal> porc { get; set; }
        public Nullable<decimal> desv { get; set; }
        public Nullable<bool> clave { get; set; }
    }
}
