//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRoomDig.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmpCargue
    {
        public int id { get; set; }
        public Nullable<int> idMaquina { get; set; }
        public string Usuario { get; set; }
        public Nullable<int> idHab { get; set; }
        public Nullable<int> idServicio { get; set; }
        public string idTarjeta { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<bool> cargada { get; set; }
    }
}
