//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRoomDig.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmpinven
    {
        public int id_maquina { get; set; }
        public string usuario { get; set; }
        public int item { get; set; }
        public Nullable<int> id_productos { get; set; }
        public Nullable<int> id_detmedidas { get; set; }
        public string convers { get; set; }
        public Nullable<int> id_convers { get; set; }
        public Nullable<double> cantidad { get; set; }
        public Nullable<double> cantiConvers { get; set; }
        public Nullable<decimal> valor { get; set; }
        public string obser { get; set; }
        public Nullable<int> id_causas { get; set; }
    }
}
