//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRoomDig.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmppago
    {
        public int id_maquina { get; set; }
        public string usuario { get; set; }
        public int item { get; set; }
        public Nullable<int> id_frmpagos { get; set; }
        public Nullable<decimal> valor { get; set; }
        public string noid { get; set; }
        public string nota { get; set; }
        public Nullable<int> cliente { get; set; }
        public Nullable<decimal> propina { get; set; }
    }
}
