//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRoomDig.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TmpResumVta
    {
        public int maquina { get; set; }
        public int id_producto { get; set; }
        public string seccion { get; set; }
        public string clase { get; set; }
        public string producto { get; set; }
        public string medida { get; set; }
        public Nullable<decimal> bar { get; set; }
        public Nullable<decimal> otrasbodegas { get; set; }
        public Nullable<decimal> totalbodega { get; set; }
        public Nullable<decimal> ventas { get; set; }
        public Nullable<decimal> promdia { get; set; }
        public Nullable<decimal> cantreq { get; set; }
        public Nullable<decimal> cantfalta { get; set; }
    }
}
