//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRoomDig.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TmpResumGral
    {
        public int maquina { get; set; }
        public int mes { get; set; }
        public int dia { get; set; }
        public int ID_COMDIA { get; set; }
        public Nullable<int> carros { get; set; }
        public Nullable<int> entradas { get; set; }
        public Nullable<decimal> bar { get; set; }
        public Nullable<decimal> bariva { get; set; }
        public Nullable<decimal> resta { get; set; }
        public Nullable<decimal> restaiva { get; set; }
        public Nullable<decimal> sencilla { get; set; }
        public Nullable<decimal> senciva { get; set; }
        public Nullable<decimal> sauna { get; set; }
        public Nullable<decimal> saunaiva { get; set; }
        public Nullable<decimal> jacuzzi { get; set; }
        public Nullable<decimal> jacuzziiva { get; set; }
        public Nullable<decimal> turco { get; set; }
        public Nullable<decimal> turcoiva { get; set; }
        public Nullable<decimal> otras { get; set; }
        public Nullable<decimal> otrasiva { get; set; }
        public Nullable<decimal> OTROS { get; set; }
        public Nullable<decimal> OTROSIVA { get; set; }
        public Nullable<decimal> CONSOTROS { get; set; }
        public Nullable<decimal> CONSOTROSIVA { get; set; }
        public Nullable<decimal> CONSTOTAL { get; set; }
        public Nullable<decimal> CONSTOTALIVA { get; set; }
        public Nullable<decimal> SERVSTOTAL { get; set; }
        public Nullable<decimal> SERVSTOTALIVA { get; set; }
        public Nullable<decimal> VTATOTAL { get; set; }
        public Nullable<decimal> VTATOTALIVA { get; set; }
    }
}
