//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRoomDig.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class toolFrmPago
    {
        public int id { get; set; }
        public Nullable<int> idFrmPago { get; set; }
        public Nullable<int> tipo { get; set; }
        public string name { get; set; }
        public Nullable<bool> uso { get; set; }
    
        public virtual frmpago frmpago { get; set; }
        public virtual frmpago frmpago1 { get; set; }
        public virtual frmpago frmpago2 { get; set; }
        public virtual frmpago frmpago3 { get; set; }
        public virtual frmpago frmpago4 { get; set; }
    }
}
