//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRoomDig.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class trfaprod
    {
        public int id_tempo { get; set; }
        public Nullable<int> id_lugar { get; set; }
        public int id_productos { get; set; }
        public int id_detmedidas { get; set; }
        public Nullable<decimal> valor { get; set; }
        public Nullable<decimal> stock_min { get; set; }
        public Nullable<decimal> stock_max { get; set; }
        public Nullable<decimal> vl_iva { get; set; }
        public Nullable<int> id_tipiva { get; set; }
        public Nullable<decimal> costo_unit { get; set; }
        public Nullable<bool> Crear { get; set; }
        public Nullable<decimal> item1 { get; set; }
        public Nullable<decimal> item2 { get; set; }
        public Nullable<decimal> item3 { get; set; }
        public Nullable<int> id_listas { get; set; }
        public Nullable<bool> COMISION { get; set; }
        public Nullable<decimal> valor_new { get; set; }
    
        public virtual detmedida detmedida { get; set; }
        public virtual producto producto { get; set; }
        public virtual temp temp { get; set; }
    }
}
