//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRoomDig.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class trfaprodsListasBak
    {
        public int id { get; set; }
        public int id_maquina { get; set; }
        public int id_productos { get; set; }
        public Nullable<decimal> min { get; set; }
        public Nullable<decimal> max { get; set; }
        public Nullable<decimal> lista1 { get; set; }
        public Nullable<decimal> lista2 { get; set; }
        public Nullable<decimal> lista3 { get; set; }
        public Nullable<decimal> lista4 { get; set; }
        public Nullable<decimal> lista5 { get; set; }
        public Nullable<decimal> lista6 { get; set; }
    }
}
