//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRoomDig.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class turnact
    {
        public int id_cierre { get; set; }
        public int id { get; set; }
        public Nullable<byte> id_tipos { get; set; }
        public Nullable<int> control { get; set; }
        public Nullable<int> id_maquinas { get; set; }
        public Nullable<int> id_usuarios { get; set; }
        public Nullable<int> id_funciones { get; set; }
        public Nullable<int> id_bodegas { get; set; }
        public Nullable<int> id_turno { get; set; }
        public Nullable<System.DateTime> fec_ini { get; set; }
        public string autor_ini { get; set; }
        public Nullable<int> id_pedido_ini { get; set; }
        public Nullable<int> id_anula_ini { get; set; }
        public Nullable<int> id_inven_ini { get; set; }
        public Nullable<int> id_consumo_ini { get; set; }
        public Nullable<int> id_factura_ini { get; set; }
        public Nullable<int> id_egreso_ini { get; set; }
        public Nullable<int> id_ingreso_ini { get; set; }
        public Nullable<int> id_propina_ini { get; set; }
        public Nullable<int> id_servicio_ini { get; set; }
        public Nullable<int> id_abono_ini { get; set; }
        public Nullable<int> id_detfac_ini { get; set; }
        public Nullable<int> id_dscto_ini { get; set; }
        public Nullable<int> id_taxi_ini { get; set; }
        public string prefijo { get; set; }
        public Nullable<int> IdNumTurno { get; set; }
    }
}
