//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRoomDig.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public Nullable<int> id { get; set; }
        public Nullable<byte> nivel { get; set; }
        public string name { get; set; }
        public Nullable<bool> turno { get; set; }
        public Nullable<int> id_funciones { get; set; }
        public string clave { get; set; }
        public Nullable<bool> temporal { get; set; }
        public Nullable<bool> CAJA { get; set; }
        public Nullable<bool> GERENCIA { get; set; }
        public Nullable<int> Autonum { get; set; }
        public string NOMBRE { get; set; }
        public string EMAIL { get; set; }
        public Nullable<bool> ACTIVO { get; set; }
        public Nullable<int> idVendePos { get; set; }
        public Nullable<int> idCentroC { get; set; }
        public string Cargo { get; set; }
        public Nullable<int> ID_CENTROC { get; set; }
    
        public virtual funcione funcione { get; set; }
    }
}
