//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRoomDig.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZMOTMP
    {
        public int id_cierre { get; set; }
        public int id { get; set; }
        public Nullable<byte> id_tipos { get; set; }
        public string id_maquinas { get; set; }
        public Nullable<int> control { get; set; }
        public Nullable<int> id_usuarios { get; set; }
        public Nullable<int> id_funciones { get; set; }
        public Nullable<int> id_bodegas { get; set; }
        public Nullable<int> id_turno { get; set; }
        public Nullable<System.DateTime> fec_ini { get; set; }
        public Nullable<System.DateTime> fec_fin { get; set; }
        public string autor_ini { get; set; }
        public string autor_fin { get; set; }
        public Nullable<int> id_pedido_ini { get; set; }
        public Nullable<int> id_pedido_fin { get; set; }
        public Nullable<int> id_anula_ini { get; set; }
        public Nullable<int> id_anula_fin { get; set; }
        public Nullable<int> id_inven_ini { get; set; }
        public Nullable<int> id_inven_fin { get; set; }
        public Nullable<int> id_consumo_ini { get; set; }
        public Nullable<int> id_consumo_fin { get; set; }
        public Nullable<int> id_factura_ini { get; set; }
        public Nullable<int> id_factura_fin { get; set; }
        public Nullable<decimal> tserfac { get; set; }
        public Nullable<decimal> tseranu { get; set; }
        public Nullable<decimal> tserpen { get; set; }
        public Nullable<decimal> tconfac { get; set; }
        public Nullable<decimal> tconanu { get; set; }
        public Nullable<decimal> tconpen { get; set; }
        public Nullable<int> id_egreso_ini { get; set; }
        public Nullable<int> id_egreso_fin { get; set; }
        public Nullable<decimal> totegreso { get; set; }
        public Nullable<int> id_ingreso_ini { get; set; }
        public Nullable<int> id_ingreso_fin { get; set; }
        public Nullable<decimal> totingreso { get; set; }
        public Nullable<int> id_propina_ini { get; set; }
        public Nullable<int> id_propina_fin { get; set; }
        public Nullable<decimal> totpropina { get; set; }
        public Nullable<int> id_servicio_ini { get; set; }
        public Nullable<int> id_servicio_fin { get; set; }
        public Nullable<int> id_abono_ini { get; set; }
        public Nullable<int> id_abono_fin { get; set; }
        public Nullable<int> id_detfac_ini { get; set; }
        public Nullable<int> id_detfac_fin { get; set; }
        public Nullable<int> id_dscto_ini { get; set; }
        public Nullable<int> id_dscto_fin { get; set; }
        public Nullable<int> id_taxi_ini { get; set; }
        public Nullable<int> id_taxi_fin { get; set; }
        public string prefijo { get; set; }
    }
}
