//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRoomDig.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class zona
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> id_area { get; set; }
        public string descrip { get; set; }
        public Nullable<bool> comput { get; set; }
        public Nullable<int> bodega { get; set; }
        public Nullable<bool> temporal { get; set; }
        public Nullable<bool> atiende { get; set; }
        public byte[] imagen { get; set; }
    
        public virtual area area { get; set; }
    }
}
