//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRoomDig.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class zzTempoProd
    {
        public int code { get; set; }
        public Nullable<int> minimo { get; set; }
        public Nullable<int> tiempo { get; set; }
        public Nullable<int> maximo { get; set; }
    }
}
